- hosts: datanode
  tasks:
  - name: "Copying Hadoop package"
    copy:
     src: "hadoop-1.2.1-1.x86_64.rpm"
     dest: "/root/"
     
  - name: "Copying Jdk File"
    copy:
     src: "jdk-8u171-linux-x64.rpm"
     dest: "/root/"
     
  - name: "Installing Jdk"
    shell: "rpm -ivh jdk-8u171-linux-x64.rpm"
    ignore_errors: yes
    
  - name: "Installing Hadoop"
    shell: "rpm -ivh hadoop-1.2.1-1.x86_64.rpm  --force"
    ignore_errors: yes
 
  - name: "Copying core-site.xml file"
    copy:
      src: "core-site.xml"
      dest: "/etc/hadoop/core-site.xml"
      
  - name: "Copying hdfs-site.xml file"
    copy:
      src: "datanode-hdfs-site.xml"
      dest: "/etc/hadoop/hdfs-site.xml"
     
  - name: "Creating a Directory"
    file:
      state: directory
      path: "dn"

  - name: "Starting the datanode"
    shell: "hadoop-daemon.sh start datanode"
    ignore_errors: yes
    
  - name: "checking status of Datanode"
    shell: "jps"
